{{- if .Values.controlPlane.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langopen.fullname" . }}-control-plane
  labels:
    {{- include "langopen.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  replicas: {{ .Values.controlPlane.replicas }}
  selector:
    matchLabels:
      {{- include "langopen.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: control-plane
  template:
    metadata:
      labels:
        {{- include "langopen.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: control-plane
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.controlPlane.runtimeClassName }}
      runtimeClassName: {{ .Values.controlPlane.runtimeClassName }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: control-plane
          image: {{ include "langopen.image" (dict "Values" .Values "component" "control-plane") | quote }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.controlPlane.service.targetPort }}
              name: http
          env:
            - name: POSTGRES_DSN
              value: {{ .Values.env.postgresDsn | quote }}
            - name: REDIS_ADDR
              value: {{ .Values.env.redisAddr | quote }}
            - name: BUILDER_URL
              value: {{ .Values.env.builderUrl | quote }}
          {{- range .Values.extraEnv.controlPlane }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- if or .Values.global.envFromSecret (gt (len .Values.extraEnvFrom.controlPlane) 0) }}
          envFrom:
            {{- if .Values.global.envFromSecret }}
            - secretRef:
                name: {{ .Values.global.envFromSecret }}
            {{- end }}
            {{- with .Values.extraEnvFrom.controlPlane }}
{{ toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            {{- toYaml .Values.controlPlane.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langopen.fullname" . }}-control-plane
  labels:
    {{- include "langopen.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: {{ .Values.controlPlane.service.type }}
  selector:
    {{- include "langopen.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  ports:
    - name: http
      port: {{ .Values.controlPlane.service.port }}
      targetPort: {{ .Values.controlPlane.service.targetPort }}
{{- end }}
